import { NextFunction, Request, Response } from 'express';
import { UserModel } from '../models';
import { UserInstance } from '../models/User';
import GroupRepository from '../repository/GroupRepository';
import successResponse from '../middleware/response';
import AppError from '../errors/AppError';
import bcrypt from 'bcryptjs';
import { generateAccessToken } from '../utils/token';
import { FindOptions } from 'sequelize/types';
import { GroupInstance } from '../models/Group';
import { Op } from 'sequelize';
import MemberRepository from '../repository/MemberRepository';
